### ISSUE TITLE
newforms isn't listed

### ISSUE THREAD

**Issue by insin** [browserify-search/www#1]
https://www.npmjs.org/package/newforms

What are the heuristics that need to be met?

**Comment by airportyh** [comment]
It turns out that newforms being dependent on punycode reduces its browserifiability score to 0 - this is just what the results in my sample data showed. I haven't checked if punycode works in browserify yet.

**Comment by airportyh** [comment]
Hmm, turns out I actually don't have any sample data about punycode usage, so it definitely shouldn't have made the conclusion that it did, so this is a bug and will be fixed. Thanks!

**Comment by airportyh** [comment]
Fixed!
